### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by xiaoiker** [xupei0610/KDMA#1]
Hi,
Thanks very much for sharing your code, this is really a great work.
But is this correct?
https://github.com/xupei0610/KDMA/blob/4d5de30fae044a05eec94b8424bb96fbfa678111/env/multi_agent_env.py#L70
As for my understanding this will not update the states in the agents. Should it be:

`self.agents[i].accelerate =...
self.agents[i].velocity =...
`

**Comment by xiaoiker** [comment]
https://github.com/xupei0610/KDMA/blob/4d5de30fae044a05eec94b8424bb96fbfa678111/models/ppo.py#L60
Also here, is this correct?

**Comment by xupei0610** [comment]
When visiting complex objects stored in a python list through a for loop or index, you will get a reference of each object such that you can change the properties of each object directly. For example,
```
class Test:
    def __init__(self, name):
        self.name = name

a = Test(name="A")
b = Test(name="B")

c = [a, b]
for e in c:
    e.name = "changed"

print(a.name)    # output: changed
print(b.name)    # output: changed

temp = c[0]
temp.name = "changed_a"
temp = c[1]
temp.name = "changed_b"
print(a.name)    # output: changed_a
print(b.name)    # output: changed_b
```

Only when accessing a simple object stored in a list, like int or float, you will get a copy of that object through which you cannot modify the value of the original object. For example:
```
a  = 1

c = [a]
c[0] = 2

print(a)        # output: 1
print(c[0])    # output: 2
```


Go back to your questions. There is no bug, since `self.agents` is a list of several Agent objects and `self.exp_cache` is a list of dict objects. You can get a reference of each object stored in these two lists by using a for loop or index, and thus directly change the values of the original properies through modifying the reference.
