### ISSUE TITLE
data structure

### ISSUE THREAD

**Issue by xiaoiker** [xupei0610/KDMA#2]
First, thanks for your previous reply.

Can I ask you another question about the data structure in the student.csv? I read the Keys() there and found that there are mainly: "x, y, vx, vy, vx_, vy_, gx, gy, gvx, gvy" . I can figure out "x, y (position), vx_, vy_ (distance to next position) , gx, gy (goal position)", but what are " vx, vy, gvx, gvy" ?

Best

**Comment by xupei0610** [comment]
Given the item with timestamp t, (vx, vy)\_t is the current velocity, namely, the velocity to reach the position (px, py)\_t from (px, py)\_(t-1).  (vx\_, vy\_)\_t is the velocity to leave from (px, py)\_t. Therefore, we have (vx\_, vy\_)\_t = (vx, vy)\_(t+1) in the dataset file. When accepting the states at timestamp t as the input, the expert network is expected to give an output as the estimation to (vx\_, vy\_)_t. 

(gvx, gvy) is the goal velocity computed according to Appendix.A in [Crowd Space: A Predictive Crowd Analysis Technique](https://people.cs.clemson.edu/~ioannis/crowd-space/). It is considered as the final leaving velocity at an agent's last timestamp. It is used only in a special case when we do interpolation at some time t' between the timestamp t0 and t1. If an agent appears as a neighbor of some other one at timestamp t0 but disappears from the dataset before the timestamp t1, we actually do not know directly whether it appears as a neighbor at t'. In that case, we estimate the position of that agent at t' by using the velocity of (gvx, gvy). For simplicity, (vx\_, vy\_) can be used as the replacement of (gvx, gvy), but it will not necessarily reflect the movement trends of an agent better than (gvx, gvy), since (1) (vx\_, vy\_) cannot be computed for the last timestamp in the raw data; and (2) the items associated with the real last few timestamps in the raw data may be removed when we do re-sampling to reduce the data recording frequency and in that case (vx\_, vy\_) is just a transient leaving velocity.

**Comment by xiaoiker** [comment]
Thanks so much for your kindness and detailed explanation. This helps a lot~

All the best!
